spring:
  datasource:
    url: jdbc:mysql://34.68.129.10:3306/chatapp_user?allowPublicKeyRetrieval=true&useSSL=false
    username: chatapp-user-mysql
    password: "{cipher}129322e7651c8809538fe6c6eee75ca276082184eba222116cfff42c1fe26ffc"

user:test: "test prop works"