spring:
  datasource:
    url: jdbc:mysql://34.68.129.10:3306/chatapp_user?allowPublicKeyRetrieval=true&useSSL=false
    username: chatapp-user-mysql
    password: "{cipher}c3f40385b06d192b0650f1e94fc1b1a9ca27a341ebe0b8c7b10ec03d86bd4617"

user:test: "test prop works"